### ISSUE TITLE
Is there a way to access V1 version online?

### ISSUE THREAD

**Issue by xfilesee34** [amvstrm/amvstrm#19]

**Comment by NYT92** [comment]
V1 is still online but since i have been switched the api to the newer version with different routes and results, the website will not be usable right now.

**Comment by xfilesee34** [comment]
thanks for your answer. is there a link for v1 version?

**Comment by NYT92** [comment]
This are the only available V1 websites that will no longer work with the new api...

https://www2.amvstr.ml
https://amvstrm.pages.dev

Dont worry all the old V1 API and website code are still here in the repo and you can self-host your own and modifying the code to make it work with the new api.
