### ISSUE TITLE
Why doesn't search work on the one I'm hosting?

### ISSUE THREAD

**Issue by Naiml007** [amvstrm/amvstrm#21]
Pls help 😭😅
![Screenshot_2023-07-17-09-45-37-807_com brave browser](https://github.com/amvstrm/amvstrm/assets/90306726/50cdf9e1-887e-4902-a5f4-223d063c3a23)

**Comment by Naiml007** [comment]
![Screenshot_2023-07-17-09-47-13-135_com brave browser](https://github.com/amvstrm/amvstrm/assets/90306726/849bc501-2450-40c5-8be6-3bae99f01b4c)

**Comment by NYT92** [comment]
![image](https://github.com/amvstrm/amvstrm/assets/53612429/a8d82771-69a0-472c-939c-016f6362b845)

I think you put "/" in the config file, try to remove it and see if it works.

**Comment by Naiml007** [comment]
Tnx ❤️
