### ISSUE TITLE
Is the search button broken?

### ISSUE THREAD

**Issue by buttlicker2** [amvstrm/amvstrm#24]
Sorry if nothings wrong with it but it doesn't work for me

**Comment by buttlicker2** [comment]
> The search is not broken for me but it is quite slow sometimes. Can you provide me with more information with a screenshot?

![Screenshot_2023-08-09-15-39-59-23_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/amvstrm/amvstrm/assets/134780389/0ad39b24-dcc0-4959-8c6e-652258428dd7)
Here it is I also waited for a few moments to test if it wasn't just my wifi or browser

**Comment by NYT92** [comment]
Oh, I realize that I forgot to fix the results list because I updated my API data from ```"data:"``` to ````"results:"```` my fault...

You can try the search page first because I just added new genres and tags filters to the page and fixed that issue too.
