### ISSUE TITLE
Anime downloading err

### ISSUE THREAD

**Issue by Naiml007** [amvstrm/amvstrm#25]
![Screenshot_2023-08-12-12-25-22-178_com brave browser](https://github.com/amvstrm/amvstrm/assets/90306726/947adc7d-3bc2-489c-b36f-72f00fa96852)

**Comment by NYT92** [comment]
api.amvstr.ml is dead, it should be api-amvstrm.nyt92.eu.org. I always forgot to change every time I work on it...

**Comment by Naiml007** [comment]
This is the code ?


![IMG_20230812_124309](https://github.com/amvstrm/amvstrm/assets/90306726/2b3316f1-d1b5-4e88-8091-227cb6fe7d00)

**Comment by NYT92** [comment]
yes just replace api.amvstr.ml to api-amvstrm.nyt92.eu.org

**Comment by Naiml007** [comment]
@NYT92

**Comment by Naiml007** [comment]
> yes just replace api.amvstr.ml to api-amvstrm.nyt92.eu.org

Ok
