### ISSUE TITLE
Render.com host doesn't work [feature]

### ISSUE THREAD

**Issue by Naiml007** [amvstrm/amvstrm#29]
![Screenshot_2023-09-22-20-27-49-800_com brave browser](https://github.com/amvstrm/amvstrm/assets/90306726/d5298203-6783-4b50-ab95-b19c98e6b73c)
![Screenshot_2023-09-22-20-23-51-897_com brave browser](https://github.com/amvstrm/amvstrm/assets/90306726/055257c8-8187-4a1f-871f-68728b595450)

**Comment by Naiml007** [comment]
![Screenshot_2023-09-22-20-30-27-873_com brave browser](https://github.com/amvstrm/amvstrm/assets/90306726/632d9768-1b1b-4b35-8c92-9bb924b9f98b)

**Comment by NYT92** [comment]
Can i see the full log of the build?

**Comment by Naiml007** [comment]
My PC has crashed, and I'm unable to copy the log using my phone.  I'm sorry 😞

**Comment by NYT92** [comment]
Ah it ok, I am gonna try to test it myself maybe I can reconfigure the render.yml file

**Comment by Naiml007** [comment]
Thank you 👍♥️

**Comment by NYT92** [comment]
I think you should configure node_version in the env or maybe try to redeploy my app  

![image](https://github.com/amvstrm/amvstrm/assets/53612429/daadfddb-139d-4c7a-88a0-90f045ddf631)

I got mine working with these configurations  

![image](https://github.com/amvstrm/amvstrm/assets/53612429/900788a9-223e-4d6c-9ac7-5d04201a04c3)

**Comment by Naiml007** [comment]
Thank you 😊 ♥️

**Comment by Naiml007** [comment]
https://amvsrm-api.onrender.com/

Build Command yarn > default

Start Command > node index.js **default** 

![270069506-900788a9-223e-4d6c-9ac7-5d04201a04c3](https://github.com/amvstrm/amvstrm/assets/90306726/52bf355f-f32d-4f64-ac6b-21580338d28e)
![Screenshot_2023-09-24-23-19-16-170_com brave browser](https://github.com/amvstrm/amvstrm/assets/90306726/5a7a2a0d-bc01-424e-889d-8cf6e19b10dd)
![Screenshot_2023-09-24-23-21-46-853_com brave browser](https://github.com/amvstrm/amvstrm/assets/90306726/b6cb8b4f-f81b-457a-8a7b-933bef1b7439)
![Screenshot_2023-09-24-23-21-55-459_com brave browser](https://github.com/amvstrm/amvstrm/assets/90306726/15a9a17e-d172-4023-8478-dfccc385d5da)
![Screenshot_2023-09-24-23-22-01-486_com brave browser](https://github.com/amvstrm/amvstrm/assets/90306726/f9d44688-75b5-47af-ae29-de9eca9d6dcb)

**Comment by Naiml007** [comment]
![Screenshot_2023-09-24-23-25-10-397_com brave browser](https://github.com/amvstrm/amvstrm/assets/90306726/012268b0-9f2a-458b-8916-bac503a450f5)

**Comment by NYT92** [comment]
Yeah thanks for the api, I need to include them in my render.yaml config later
