### ISSUE TITLE
Video Quality Choices

### ISSUE THREAD

**Issue by WarLock03** [amvstrm/amvstrm#35]
The api does not have a video quality choices and download link, how can I access it sir?

**Comment by NYT92** [comment]
We get stream data from gogo and provide a download page on the website. Our API cannot scrape the video link from the gogo embed site (reason: required captcha), but we do have an API that gets the download URL instead.

**Comment by WarLock03** [comment]
What's the api to download link sir? The api https://api.amvstr.me/api/v2/
docs do not have one

**Comment by WarLock03** [comment]
And also video quality choices?
