### ISSUE TITLE
Maintainence mode

### ISSUE THREAD

**Issue by iotserver24** [amvstrm/amvstrm#47]
about the Api
I want to host it in Cloudflare workers as its best option for all but I can't idk why though
also
is it possible to make it show only animes name and excluding manga names coz its bit disturbing
by the way thx for this masterpiece website

**Comment by NYT92** [comment]
You should make an issue on the API repo but i will answer here anyway.

You can just use cloudflare worker to do that but i just dont like their limitation since the website need to fetch a lot of information. For other issue, I cannot exclude them from the API but in the website, we do lock the button, if we cannot find both episode and anime mark it as not available.

**Comment by NYT92** [comment]
The env file is where you config the API_URL and version should be v2

**Comment by iotserver24** [comment]
thank you!

**Comment by iotserver24** [comment]
hey i made small changes in aniqery.js
and now it shows only animes
i will give the file wait

**Comment by NYT92** [comment]
You can create a PR request at the api repo. I appreciate the changes that you made.

**Comment by iotserver24** [comment]
https://www.dropbox.com/scl/fi/1ejk9u3rofo0mkhu4xis6/aniquery.js?rlkey=64ph8d1igya3ccy8ttgq89gqz&st=0xactb64&dl=0
heres the file
idk how to PR request sry

**Comment by iotserver24** [comment]
also can you say where have o hosted the api coz i dont earn rn and i am sure i will recieveas i build the APPLICATION FOR ALLL DEVICES (ofc except for iphone and mac)
so can you say which can run without sleep pls

**Comment by NYT92** [comment]
I made an API change to the stream route last month (mentioned in #41). Now I already fixed the issue and deployed it to the web after that. You might want to wait till I push some new changes to the repo later but I still need to test all the features before I push.

**Comment by iotserver24** [comment]
no no what I mean is rn its not working
also when will it be back from maintenance 
coz render is not working
meanwhile
vercel doesnt even fetch anything

**Comment by NYT92** [comment]
Ah i see

**Comment by iotserver24** [comment]
so when will you release from mainteneace?
also did you try what i gave?

**Comment by NYT92** [comment]
It worked fine, I'll open it again for a few days and also push the changes too.

**Comment by iotserver24** [comment]
thx
😆

**Comment by iotserver24** [comment]
can you say when will you release the api again
also pls say which is good server to host api for free which is fast and does not have long sleeptime
pls say coz api request will surely crosss 300 a minute so

**Comment by NYT92** [comment]
Railway, render, fly, and vercel is my only option but even though they do have downside, it can still host the api perfectly fine.

**Comment by iotserver24** [comment]
I mean which will have least sleeptime so that it could run fast

**Comment by NYT92** [comment]
> I mean which will have least sleeptime so that it could run fast

Use railways, they run forever but consume quite a bit credit so be careful.

**Comment by iotserver24** [comment]
ok thx

**Comment by iotserver24** [comment]
hey rn i hosted your api by forking and ran it in vercel buit wont load anime and get these errors


Access to fetch at 'https://avapi.vercel.app//api/V2/trending?limit=12' from origin 'XXXXXXXXXX' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
C4fCXHp2.js:18 
        
        
        GET https://avapi.vercel.app//api/V2/trending?limit=12 net::ERR_FAILED
i @ C4fCXHp2.js:18
s @ C4fCXHp2.js:18
i @ C4fCXHp2.js:18
await in i (async)
o @ C4fCXHp2.js:18
(anonymous) @ C4fCXHp2.js:24
Promise.then._ @ C4fCXHp2.js:24
Q1.u.refresh.u.execute @ C4fCXHp2.js:24
f @ C4fCXHp2.js:24
Q1 @ C4fCXHp2.js:24
Og @ C4fCXHp2.js:24
setup @ CLcVDj1j.js:1
jn @ C4fCXHp2.js:14
c_ @ C4fCXHp2.js:14
u_ @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
my @ C4fCXHp2.js:14
process @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
R @ C4fCXHp2.js:14
I @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
R @ C4fCXHp2.js:14
I @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
R @ C4fCXHp2.js:14
S @ C4fCXHp2.js:14
k @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
(anonymous) @ C4fCXHp2.js:14
Promise.then (async)
registerDep @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
R @ C4fCXHp2.js:14
I @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
R @ C4fCXHp2.js:14
I @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
my @ C4fCXHp2.js:14
process @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
R @ C4fCXHp2.js:14
S @ C4fCXHp2.js:14
k @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
R @ C4fCXHp2.js:14
S @ C4fCXHp2.js:14
k @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
(anonymous) @ C4fCXHp2.js:14
Promise.then (async)
registerDep @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
my @ C4fCXHp2.js:14
process @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
R @ C4fCXHp2.js:14
I @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
(anonymous) @ C4fCXHp2.js:14
Promise.then (async)
registerDep @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
my @ C4fCXHp2.js:14
process @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
K @ C4fCXHp2.js:14
mount @ C4fCXHp2.js:14
V_.t.mount @ C4fCXHp2.js:18
hh @ C4fCXHp2.js:33
await in hh (async)
(anonymous) @ C4fCXHp2.js:33
pwa:1  Access to fetch at 'https://avapi.vercel.app//api/V2/popular?limit=12' from origin 'XXXXXXXXXXXX' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
C4fCXHp2.js:18 
        
        
        GET https://avapi.vercel.app//api/V2/popular?limit=12 net::ERR_FAILED
i @ C4fCXHp2.js:18
o @ C4fCXHp2.js:18
(anonymous) @ C4fCXHp2.js:24
Promise.then._ @ C4fCXHp2.js:24
Q1.u.refresh.u.execute @ C4fCXHp2.js:24
f @ C4fCXHp2.js:24
Q1 @ C4fCXHp2.js:24
Og @ C4fCXHp2.js:24
setup @ CLcVDj1j.js:1
jn @ C4fCXHp2.js:14
c_ @ C4fCXHp2.js:14
u_ @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
my @ C4fCXHp2.js:14
process @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
R @ C4fCXHp2.js:14
I @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
R @ C4fCXHp2.js:14
I @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
R @ C4fCXHp2.js:14
S @ C4fCXHp2.js:14
k @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
(anonymous) @ C4fCXHp2.js:14
Promise.then (async)
registerDep @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
R @ C4fCXHp2.js:14
I @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
R @ C4fCXHp2.js:14
I @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
my @ C4fCXHp2.js:14
process @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
R @ C4fCXHp2.js:14
S @ C4fCXHp2.js:14
k @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
R @ C4fCXHp2.js:14
S @ C4fCXHp2.js:14
k @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
(anonymous) @ C4fCXHp2.js:14
Promise.then (async)
registerDep @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
my @ C4fCXHp2.js:14
process @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
R @ C4fCXHp2.js:14
I @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
(anonymous) @ C4fCXHp2.js:14
Promise.then (async)
registerDep @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
my @ C4fCXHp2.js:14
process @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
K @ C4fCXHp2.js:14
mount @ C4fCXHp2.js:14
V_.t.mount @ C4fCXHp2.js:18
hh @ C4fCXHp2.js:33
await in hh (async)
(anonymous) @ C4fCXHp2.js:33
pwa:1  Access to fetch at 'https://avapi.vercel.app//api/V2/popular?limit=12' from origin 'XXXXXXXXXXXXXX' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
C4fCXHp2.js:18 
        
        
        GET https://avapi.vercel.app//api/V2/popular?limit=12 net::ERR_FAILED
i @ C4fCXHp2.js:18
s @ C4fCXHp2.js:18
i @ C4fCXHp2.js:18
await in i (async)
o @ C4fCXHp2.js:18
(anonymous) @ C4fCXHp2.js:24
Promise.then._ @ C4fCXHp2.js:24
Q1.u.refresh.u.execute @ C4fCXHp2.js:24
f @ C4fCXHp2.js:24
Q1 @ C4fCXHp2.js:24
Og @ C4fCXHp2.js:24
setup @ CLcVDj1j.js:1
jn @ C4fCXHp2.js:14
c_ @ C4fCXHp2.js:14
u_ @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
my @ C4fCXHp2.js:14
process @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
R @ C4fCXHp2.js:14
I @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
R @ C4fCXHp2.js:14
I @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
R @ C4fCXHp2.js:14
S @ C4fCXHp2.js:14
k @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
(anonymous) @ C4fCXHp2.js:14
Promise.then (async)
registerDep @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
R @ C4fCXHp2.js:14
I @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
R @ C4fCXHp2.js:14
I @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
my @ C4fCXHp2.js:14
process @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
R @ C4fCXHp2.js:14
S @ C4fCXHp2.js:14
k @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
R @ C4fCXHp2.js:14
S @ C4fCXHp2.js:14
k @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
(anonymous) @ C4fCXHp2.js:14
Promise.then (async)
registerDep @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
my @ C4fCXHp2.js:14
process @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
R @ C4fCXHp2.js:14
I @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
(anonymous) @ C4fCXHp2.js:14
Promise.then (async)
registerDep @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
my @ C4fCXHp2.js:14
process @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
B @ C4fCXHp2.js:14
run @ C4fCXHp2.js:10
H.v.update @ C4fCXHp2.js:14
H @ C4fCXHp2.js:14
se @ C4fCXHp2.js:14
q @ C4fCXHp2.js:14
p @ C4fCXHp2.js:14
K @ C4fCXHp2.js:14
mount @ C4fCXHp2.js:14
V_.t.mount @ C4fCXHp2.js:18
hh @ C4fCXHp2.js:33
await in hh (async)
(anonymous) @ C4fCXHp2.js:33



so pls help

**Comment by NYT92** [comment]
Show me your env config

**Comment by iotserver24** [comment]
this is of site
API_URL=https://avapi.vercel.app/
VERSION=V2

# optional
DISQUS_ID=
POSTHOG_PK=phc_3uZeEYKW5GehMedgLjLQqxRmeBeZEravWwZGpn7EkYP
POSTHOG_HOST=https://us.i.posthog.com

this is of api :below
RATE_LIMIT=1000
ALLOWLIST=https://animeverse.cc,https://av4web.pages.dev
BLOCK_WITH_CORS=false
SENTRY_DSN_URL=
PORT=8080
USE_REDIS=false
REDIS_APP_URL=

**Comment by NYT92** [comment]
The API seems fine nothing wrong but I noticed in your website that you added '/' at the end of the api URL causing cors error that means page does not exist

**Comment by iotserver24** [comment]
pls say where 
i mean in which page

**Comment by iotserver24** [comment]
wait .......
just '/' was the one which was near disturbing me for 2 weeks!
thx a lot it fixed!!

**Comment by iotserver24** [comment]
pls do this one last update
in player even if we swipe a little it will move so make it like hold screen for 3sec and then move to move the episode pls
after update pls send the file

**Comment by iotserver24** [comment]
can you fix it?
