### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by iotserver24** [amvstrm/amvstrm#50]
Latest animes that are released are not available like suicide squad isekai etc

**Comment by NYT92** [comment]
Since we use bal-mackup/mal-backup as a source, we could not guaranteed all the data is 100% stable. I need to wait for the owner to update the repo source. 

Sorry for ignoring your replies also because I've just finished monthly exam

**Comment by iotserver24** [comment]
> Since we use bal-mackup/mal-backup as a source, we could not guaranteed all the data is 100% stable & accurate. I need to wait for the owner to update the repo source.
> 
> Sorry for ignoring your replies also because I've just finished monthly exam

p coz actually i am disturbing you rn when you were happy as just the exam have been ended ( meanwhile mine 12th completed(in India) result came, god marks in my body for less marks and got seat for engineering 😅 )
also can you add a new epi released part where it shows new episodes released pls?

**Comment by NYT92** [comment]
Yeah nice for you and also I will find a way to fix and release the issue soon. I haven't touched the code that much but am still pushing updates occasionally because of DDoS stuff and breaking changes.

**Comment by iotserver24** [comment]
> I haven't touched the code that much but am still pushing updates occasionally because of DDoS stuff and breaking changes
  do you use telegram or any other that i can contact you for help or code suggestion easily than this 😅

**Comment by NYT92** [comment]
my discord me at nyt92#1075

**Comment by iotserver24** [comment]
i dont use discord 😅 but i will download now

**Comment by iotserver24** [comment]
![image](https://github.com/amvstrm/amvstrm/assets/147928812/3af09534-a049-473d-87f9-84ab691a26b4)
see 
this is mine: r3ap3redit

**Comment by NYT92** [comment]
I will add you

**Comment by iotserver24** [comment]
ok thx
