### ISSUE TITLE
Can someone help me please 

### ISSUE THREAD

**Issue by anime-kun32** [amvstrm/amvstrm#54]
I am filling in the .env file and so it is version 2 of the API i'm using , the question is do I have to include V2 in the API and V2 or just 2 in the API version

**Comment by NYT92** [comment]
The ``VERSION`` in the env file should be "v2" by default

**Comment by anime-kun32** [comment]
Then in the API so I can to put V2 as well

**Comment by NYT92** [comment]
make sure not to include the whole ```/api/v2``` url just only the url of the api like ```https://api.----.---```. You can see the example of the config [here](https://github.com/amvstrm/docs/blob/8686baa31e582cdab291fe39fffa58f780be3a09/content/2.guide/0.configuration.md)
