### ISSUE TITLE
A quick question please 

### ISSUE THREAD

**Issue by anime-kun32** [amvstrm/amvstrm#57]
What exactly does a disqus id look like I can't seem to find it

**Comment by NYT92** [comment]
It a service that allows you to add comment to the website. If you plan to add them, you can signup and integrate them to the website

**Comment by anime-kun32** [comment]
How does the id look like because I have had an account like a year ago , I normally integrate them using the universal code is it a URL or a username

**Comment by NYT92** [comment]
> How does the id look like because I have had an account like a year ago , I normally integrate them using the universal code is it a URL or a username 

It should be your id from "https://(your id).disqus.com"
