### ISSUE TITLE
Question about forking and deploying on railway

### ISSUE THREAD

**Issue by SyncXII** [amvstrm/amvstrm#60]
Hello sir @NYT92. First of all, thank you for the awesome work!

So I was just wondering if its possible to deploy the app and use your api to make a mirror/clone of an actual functional streaming site? Because I tried deploying it on railway and can't seem to fetch and make the website work even if I added the amvstrm api v2 on the railway config settings.

Thank you!

**Comment by NYT92** [comment]
If you have a CORS issue, you either need to config the code and set the Cors function like this
```js
router.use(
  "/",
  cors({origin: "*"})
```
or you might want to set ``BLOCK_WITH_CORS`` to true and add the domain to the ``ALLOWLIST`` (This will accept multiple domains).

**Comment by SyncXII** [comment]
> If you have a CORS issue, you either need to config the code and set the Cors function like this
> 
> ```js
> router.use(
>   "/",
>   cors({origin: "*"})
> ```
> 
> or you might want to set `BLOCK_WITH_CORS` to true and add the domain to the `ALLOWLIST` (This will accept multiple domains). Sorry for that problem, I am working on the fixes on that and also in the process of switching the framework to Elysia.

Thank you for the response. Sorry to ask, but which folder/file can I find the config? Can't seem to find it inside the repo. Is it okay if we can talk via discord or something? Thanks!

Discord:
synczxc

**Comment by NYT92** [comment]
This is the file https://github.com/amvstrm/api/blob/master/src/routes/index.js

**Comment by SyncXII** [comment]
> This is the file https://github.com/amvstrm/api/blob/19810acc1cc2509ec0ee73f876558a387ea591bd/src/routes/index.js#L53-L67

I see, so I have to host the api myself or something to make it work on the forked amvstream site work? Sorry mostly just beginner at these kind of stuffs.

**Comment by NYT92** [comment]
The public API is used for testing and app module purposes but we highly recommend to self-host your own one instead.

**Comment by SyncXII** [comment]
> The public API is used for testing and app module purposes but we highly recommend self-hosting your own one by forking the API code and deploying it to any provider instead.

I see, so that's why it was not working. Thank you for the info and will try it out. Kudos to your work Sir. Keep it up!

**Comment by NYT92** [comment]
No problems

**Comment by SyncXII** [comment]
> No problems

Tried the cors code u gave but doesnt seem still to work on railway. Even added the same reference you linked me and added my domain in the allowlist. Cant seem to still load the sources.

Sent you a dm on twitter, if its alright to ask there. 

Thanks!
