### ISSUE TITLE
Could you add art player.js control lock feature 

### ISSUE THREAD

**Issue by anime-kun32** [amvstrm/amvstrm#63]
**What feature would you like to see?**
I thought you should add a control lock feature  so when scrolling on the page , you don't accidentally interact with the player

**Comment by NYT92** [comment]
So you want the locked the play, seeking and setting stuff to the player right?

**Comment by NYT92** [comment]
Artplayer does support the lock feature but only for mobile layout that can be activated

**Comment by anime-kun32** [comment]
exactly  my point , normally when i try to scroll on the watch page , i normally interact , with the player , unlike desktop one can use the arrow keys or the scroll bar

**Comment by NYT92** [comment]
Aight might add them in the next update. Let me see what I can do

**Comment by anime-kun32** [comment]
😀😀
