### ISSUE TITLE
So is it me or? [bug]

### ISSUE THREAD

**Issue by wasplan** [amvstrm/amvstrm#71]
When I tried to watch an anime it only loads and keeps loading and doesnt work either idk what is this issue? maybe backend cant fetch the episodes anymore because gogoanime patched it.

**Comment by NYT92** [comment]
Gogoanime or vidstream did patch the stream with CORS sadly but we did have some solutions available here in our docs 
https://docs.amvstr.me/faq.html#cors-error

**Comment by NYT92** [comment]
It does work but the stream will still have the CORS error that means that only s3taku or any vidstream site can stream the content to their site

**Comment by wasplan** [comment]
alr alr big guy what do you think about AniWatch/HiAnime Api?
